# Infrastructure as Code file for render.com
services:
  - type: web
    name: roralisBackend
    env: docker
    repo: https://github.com/andrei-io/roralis.git
    region: frankfurt
    branch: prod-server
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: roralisPostgres
          property: connectionString

databases:
  - name: roralisPostgres
    region: frankfurt
    databaseName: roralis
