version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: unless-stopped


  adminer:
    depends_on:
      - db
    image: adminer:4.8.1
    ports:
      - 8090:8080
    restart: unless-stopped