version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ${DOCKER_VOLUME_LOCATION}/countryroads/postrges:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: unless-stopped


  adminer:
    depends_on:
      - db
    image: adminer:4.8.1
    ports:
      - 8090:8080
    restart: unless-stopped
  
  cache:
    image: redis:6.2.6
    ports:
      - 6379:6379
    restart: unless-stopped

  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DB_URL=host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable
      - SENDGRID_KEY=${SENDGRID_KEY}
      - EMAIL_NAME=${EMAIL_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - ENV=DEV
      - REDIS_ADDRESS=cache:6379
      - REDIS_PASSWORD=
      - JWT_PUBLIC=${JWT_PUBLIC}
      - JWT_PRIVATE=${JWT_PRIVATE}

