name: Lint, Build and Test

on:
  push:
    paths:
      - 'backend/*'
  pull_request:
    paths:
      - 'backend/*'

jobs:
  lint_and_test:
    name: Lint, Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # Set up GO SDK
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Cache go mod cache, used to speedup builds
      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...

      # Lint
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          skip-go-installation: true
          working-directory: ./backend
